version: 2.1

orbs:
  win: circleci/windows@2.2.0 

workflows:
  build-and-unittest:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    executor:
      name: win/default
      version: stable
    steps:
      - checkout
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore src\Cfd
      - run:
          name: Build project 
          command: dotnet build src\Cfd
      - run:
          name: "Running tests"
          command: |
            mkdir test-results
            dotnet test ./Cfd.Tests --logger:"junit;LogFilePath=test-results/dotnet-sample-cfd/xunit.xml"
      - store_test_results:
          path: ./Cfd.Tests/test-results
      - store_artifacts:
          path: ./Cfd.Tests/test-results
  
   
    

      
            
